version: "3.9"

volumes:
  postgres_volume:
    driver: local
  pgadmin_volume:
    driver: local

services:
  postgres:
    restart: always
    container_name: postgres_keycloak
    image: postgres:15.3
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    networks:
      - keycloak_network
  pgadmin:
    container_name: pgadmin_keycloak
    image: dpage/pgadmin4:7.3
    volumes:
      - pgadmin_volume:/var/lib/pgadmin/data
    env_file:
      - postgres.env
    ports:
      - "8280:80"
    networks:
      - keycloak_network
  keycloak:
    container_name: keycloak_server
    image: quay.io/keycloak/keycloak:22.0.1
    env_file:
      - keycloak.env
    command: start-dev
    ports:
      - "8580:8080"
    depends_on:
      - postgres
    networks:
      - keycloak_network

networks:
  keycloak_network:
    name: keycloak_network
    driver: bridge